export const mouCompanies = [
  { "name": "Tata ConSultancy Service Limited (TCS), Chennai", "image": "/mou/Tata_ConSultancy_Service_Limited__TCS___Chennai.png" },
  { "name": "Bharath sanchar Niham Limited (BSNL), Chennai", "image": "/mou/Bharath_sanchar_Niham_Limited__BSNL___Chennai.png" },
  { "name": "Micro Genesis (IBM), Chennai", "image": "/mou/Micro_Genesis__IBM___Chennai.png" },
  { "name": "Sun Paper Mill Limited, Cheranmahadevi", "image": "/mou/Sun_Paper_Mill_Limited__Cheranmahadevi.png" },
  { "name": "Madura Coats Private Limited, papavinasan", "image": "/mou/Madura_Coats_Private_Limited__papavinasan.png" },
  { "name": "Sutherland Global services Private Limited, Chennai", "image": "/mou/Sutherland_Global_services_Private_Limited__Chennai.png" },
  { "name": "Vi Microsystems Private Limited, Chennai", "image": "/mou/Vi_Microsystems_Private_Limited__Chennai.png" },
  { "name": "Dharangadhara Chemical works Ltd,Sahupuram", "image": "/mou/Dharangadhara_Chemical_works_Ltd_Sahupuram.png" },
  { "name": "Falcon Electro-Tek Private Limited,Mumbai", "image": "/mou/Falcon_Electro_Tek_Private_Limited_Mumbai.png" },
  { "name": "Southern Scientific Instruments, Chennai", "image": "/mou/Southern_Scientific_Instruments__Chennai.png" },
  { "name": "Kalpaka Chemicals (P) Limited, Tuticorin", "image": "/mou/Kalpaka_Chemicals__P__Limited__Tuticorin.png" },
  { "name": "Prompt Technology Solutions, Vallioor", "image": "/mou/Prompt_Technology_Solutions__Vallioor.png" },
  { "name": "Vyosoft Solutions, Chennai", "image": "/mou/Vyosoft_Solutions__Chennai.png" },
  { "name": "Kenriche Technologies (P) Ltd., Chennai", "image": "/mou/Kenriche_Technologies__P__Ltd___Chennai.png" },
  { "name": "Surya Services, Erode", "image": "/mou/Surya_Services__Erode.png" },
  { "name": "Nissi Engineering Solutions,Rajapalayam", "image": "/mou/Nissi_Engineering_Solutions_Rajapalayam.png" },
  { "name": "Junior Chamber International, TAC Nagar, Thoothukudi", "image": "/mou/Junior_Chamber_International__TAC_Nagar__Thoothukudi.png" },
  { "name": "Sivanthi Academy,Tiruchendur", "image": "/mou/Sivanthi_Academy_Tiruchendur.png" },
  { "name": "Interpress Private Ltd,Chennai", "image": "/mou/Interpress_Private_Ltd_Chennai.png" },
  { "name": "Elysium Technologies (P) Ltd,Madurai", "image": "/mou/Elysium_Technologies__P__Ltd_Madurai.png" },
  { "name": "N.D.S. Pipe Industries, Nagercoil", "image": "/mou/N_D_S__Pipe_Industries__Nagercoil.png" },
  { "name": "Siva Packaging Industries,Nagercoil", "image": "/mou/Siva_Packaging_Industries_Nagercoil.png" },
  { "name": "G.K.Industries,Konam", "image": "/mou/G_K_Industries_Konam.png" },
  { "name": "Agile Programmers Private Limited,Chennai", "image": "/mou/Agile_Programmers_Private_Limited_Chennai.png" },
  { "name": "KAC Equipments Co.,Coimbatore", "image": "/mou/KAC_Equipments_Co__Coimbatore.png" },
  { "name": "Invictus Technology Solutions (P) Ltd, Chennai.", "image": "/mou/Invictus_Technology_Solutions__P__Ltd__Chennai_.png" },
  { "name": "Sarmal Soft, Thoothukudi", "image": "/mou/Sarmal_Soft__Thoothukudi.png" },
  { "name": "Jayam Consultants Private Ltd, Chennai", "image": "/mou/Jayam_Consultants_Private_Ltd__Chennai.png" },
  { "name": "Deccan Construction Company, Tirunelveli", "image": "/mou/Deccan_Construction_Company__Tirunelveli.png" },
  { "name": "Karthikeyan Brickworks, Tuticorin", "image": "/mou/Karthikeyan_Brickworks__Tuticorin.png" },
  { "name": "Barani Flash Bricks, Campellabad", "image": "/mou/Barani_Flash_Bricks__Campellabad.png" },
  { "name": "Kingston University , London", "image": "/mou/Kingston_University___London.png" },
  { "name": "Hypotech Solutions , Coimbatore", "image": "/mou/Hypotech_Solutions___Coimbatore.png" },
  { "name": "EquilivisionTechnologies , Tiruvananthapuram", "image": "/mou/EquilivisionTechnologies___Tiruvananthapuram.png" },
  { "name": "Cloud Region Technologies", "image": "/mou/Cloud_Region_Technologies.png" },
  { "name": "University of Malaya,Malaysia", "image": "/mou/University_of_Malaya_Malaysia.png" },
  { "name": "AdroIT Technologies, Coimbatore.", "image": "/mou/AdroIT_Technologies__Coimbatore_.png" },
  { "name": "Mistral Solutions, Bangalore.", "image": "/mou/Mistral_Solutions__Bangalore_.png" },
  { "name": "Suzlon Infrastructure services Ltd", "image": "/mou/Suzlon_Infrastructure_services_Ltd.png" },
  { "name": "Marlen India Pvt Ltd, Chennai", "image": "/mou/Marlen_India_Pvt_Ltd__Chennai.png" },
  { "name": "Blesssoft Corporation, Karaikal", "image": "/mou/Blesssoft_Corporation__Karaikal.png" },
  { "name": "G2G Technologies.", "image": "/mou/G2G_Technologies_.png" },
  { "name": "Shizuvoka university , Japan.", "image": "/mou/Shizuvoka_university___Japan_.png" },
  { "name": "NI Drive-Tokyo", "image": "/mou/NI_Drive_Tokyo.png" },
  { "name": "AB Technologies", "image": "/mou/AB_Technologies.png" },
  { "name": "AdroIT Technologies-Coimbatore", "image": "/mou/AdroIT_Technologies_Coimbatore.png" },
  { "name": "Srishti Innovative Computer Systems Pvt. Ltd-Thiruvananathapuram", "image": "/mou/Srishti_Innovative_Computer_Systems_Pvt__Ltd_Thiruvananathapuram.png" },
  { "name": "Tech Power Solutions- Nagercovil", "image": "/mou/Tech_Power_Solutions__Nagercovil.png" }
];
