export const placementData2022_2023 = [
  { sno: 1, name: "Abdul Fazil K", dept: "CSE", employer: "Postulate", type: "Off Campus", salary: "3 LPA" },
  { sno: 2, name: "Aravindaloshaman C", dept: "CSE", employer: "Postulate", type: "Off Campus", salary: "3 LPA" },
  { sno: 3, name: "Bala Pradeep J", dept: "CSE", employer: "Aspro Technologies", type: "Off Campus", salary: "3.2 LPA" },
  { sno: 4, name: "Daniel Porraj P", dept: "CSE", employer: "Postulate", type: "Off Campus", salary: "3 LPA" },
  { sno: 5, name: "A. Esakkimuthu", dept: "CSE", employer: "Centizen", type: "On Campus", salary: "3.07 LPA" },
  { sno: 6, name: "Harish Raja B", dept: "CSE", employer: "Tata Consultancy Services", type: "Off Campus", salary: "3.36 LPA" },
  { sno: 7, name: "Jegatheesh R", dept: "CSE", employer: "Mistral Solution", type: "On Campus", salary: "5 LPA" },
  { sno: 8, name: "Jenish Livingston J", dept: "CSE", employer: "N.S.N Finance & Investments Pvt Ltd", type: "On Campus", salary: "3 LPA" },
  { sno: 9, name: "KathiravanVikash N", dept: "CSE", employer: "UTL Dev Holding Software Services", type: "On Campus", salary: "2.8 LPA" },
  { sno: 10, name: "Kavya J", dept: "CSE", employer: "Mistral Solution", type: "On Campus", salary: "5 LPA" },
  { sno: 11, name: "Lakshana L", dept: "CSE", employer: "Aspro Technologies", type: "Off Campus", salary: "3.2 LPA" },
  { sno: 12, name: "Mahesh Kumar G", dept: "CSE", employer: "Aspro Technologies", type: "Off Campus", salary: "3.2 LPA" },
  { sno: 13, name: "Madhavan K", dept: "CSE", employer: "Aspro Technologies", type: "Off Campus", salary: "3.2 LPA" },
  { sno: 14, name: "MuthuCopalaSaravanan M", dept: "CSE", employer: "UTH Dev Holding Software Services", type: "On Campus", salary: "2.8 LPA" },
  { sno: 15, name: "Nithisia S", dept: "CSE", employer: "Centizen", type: "On Campus", salary: "3.07 LPA" },
  { sno: 16, name: "PonVignesh R", dept: "CSE", employer: "UTH Dev Holding Software Services", type: "On Campus", salary: "2.8 LPA" },
  { sno: 17, name: "Prabhu Raj M", dept: "CSE", employer: "Aspro Technologies", type: "Off Campus", salary: "3.2 LPA" },
  { sno: 18, name: "Praveen N", dept: "CSE", employer: "UTH Dev Holding Software Services", type: "On Campus", salary: "2.8 LPA" },
  { sno: 19, name: "Pravin Kumar S", dept: "CSE", employer: "UTH Dev Holding Software Services", type: "On Campus", salary: "2.8 LPA" },
  { sno: 20, name: "PreethiRajeswari R", dept: "CSE", employer: "HNS Technologies", type: "Off Campus", salary: "2.16 LPA" },
  { sno: 21, name: "PremaKalyan M", dept: "CSE", employer: "UTH Dev Holding Software Services", type: "On Campus", salary: "2.8 LPA" },
  { sno: 22, name: "RithvickRoshan K", dept: "CSE", employer: "Centizen", type: "On Campus", salary: "3.07 LPA" },
  { sno: 23, name: "Sharon Renisha S", dept: "CSE", employer: "UTH Dev Holding Software Services", type: "On Campus", salary: "2.8 LPA" },
  { sno: 24, name: "Shunmugapavithra B", dept: "CSE", employer: "SURESOFT", type: "On Campus", salary: "2.7 LPA" },
  { sno: 25, name: "Siva Balan V", dept: "CSE", employer: "Vinsinfo", type: "On Campus", salary: "3.3 LPA" },
  { sno: 26, name: "Sivasakthi V", dept: "CSE", employer: "UTH Dev Holding Software Services", type: "On Campus", salary: "2.8 LPA" },
  { sno: 27, name: "Siva Subramanian G", dept: "CSE", employer: "HNS Technologies", type: "Off Campus", salary: "2.16 LPA" },
  { sno: 28, name: "Sornavalli H", dept: "CSE", employer: "Maxvy Technologies", type: "On Campus", salary: "3 LPA" },
  { sno: 29, name: "Sowmiga C", dept: "CSE", employer: "Tata Consultancy Services", type: "Off Campus", salary: "3.4 LPA" },
  { sno: 30, name: "Subramanian N", dept: "CSE", employer: "UTH Dev Holding Software Services", type: "On Campus", salary: "2.8 LPA" },
  { sno: 31, name: "Swetha S", dept: "CSE", employer: "HNS Technologies", type: "Off Campus", salary: "2.52 LPA" },
  { sno: 32, name: "Vana Raja A", dept: "CSE", employer: "UTH Dev Holding Software Services", type: "On Campus", salary: "2.8 LPA" },
  { sno: 33, name: "Vinceyvathy. G", dept: "CSE", employer: "UTH Dev Holding Software Services", type: "On Campus", salary: "2.8 LPA" },
  { sno: 34, name: "E.Boobana", dept: "IT", employer: "Mistral Solutions Pvt Ltd – Bangalore", type: "On Campus", salary: "5 LPA" },
  { sno: 35, name: "Rajalakshmi. C", dept: "IT", employer: "CentizenInc-TirunelVeli", type: "On Campus", salary: "4 LPA" },
  { sno: 36, name: "Pravin", dept: "IT", employer: "Zuci Systems", type: "On Campus", salary: "4 LPA" },
  { sno: 37, name: "HirthicShyam R", dept: "IT", employer: "MAXVY Technologies - Bangalore", type: "On Campus", salary: "3 LPA" },
  { sno: 38, name: "Swedha S", dept: "IT", employer: "MAXVY Technologies - Bangalore", type: "On Campus", salary: "3 LPA" },
  { sno: 39, name: "Veera Lakshmi", dept: "IT", employer: "TCS-Chennai", type: "On Campus", salary: "3.3 LPA" },
  { sno: 40, name: "Mohana R", dept: "IT", employer: "Suresoft Systems – Pondicherry", type: "On Campus", salary: "2 LPA" },
  { sno: 41, name: "IruthayaSanthiya", dept: "IT", employer: "Digital Wordsings Services", type: "Off Campus", salary: "1.5 LPA" },
  { sno: 42, name: "Mohideen Kamal", dept: "IT", employer: "UTH Dev Holding Software Services", type: "On Campus", salary: "2.4 LPA" },
  { sno: 43, name: "SabiyaPriya", dept: "IT", employer: "AlosSynel", type: "On Campus", salary: "5 LPA" },
  { sno: 44, name: "Kavshiya K", dept: "ECE", employer: "Mistral Solutions Pvt Ltd – Bangalore", type: "On Campus", salary: "5 LPA" },
  { sno: 45, name: "Niveda J", dept: "ECE", employer: "Mistral Solutions Pvt Ltd – Bangalore", type: "On Campus", salary: "5 LPA" },
  { sno: 46, name: "MuthuSweatha", dept: "ECE", employer: "Zoho Corporation – Chennai", type: "On Campus", salary: "6 LPA" },
  { sno: 47, name: "Vijaya Lakshmi", dept: "ECE", employer: "Vinsinfo – Chennai", type: "On Campus", salary: "3 LPA" },
  { sno: 48, name: "Priya", dept: "ECE", employer: "Datapatterns – Chennai", type: "On Campus", salary: "3 LPA" },
  { sno: 49, name: "Iswarya S", dept: "ECE", employer: "TEKION", type: "On Campus", salary: "11 LPA" },
  { sno: 50, name: "Jeyasri S", dept: "ECE", employer: "SRI Analytics – Chennai", type: "On Campus", salary: "4 LPA" },
  { sno: 51, name: "ShanmugaSundari N", dept: "ECE", employer: "MAXVY Technologies – Bangalore", type: "On Campus", salary: "3 LPA" },
  { sno: 52, name: "Kanmani K", dept: "ECE", employer: "MAXVY Technologies – Bangalore", type: "On Campus", salary: "3 LPA" },
  { sno: 53, name: "SubbulSivasanthari", dept: "ECE", employer: "MAXVY Technologies – Bangalore", type: "On Campus", salary: "3 LPA" },
  { sno: 54, name: "Sanjula G A", dept: "ECE", employer: "RR Electronics – Chennai", type: "Off Campus", salary: "1.5 LPA" },
  { sno: 55, name: "AnishaBrightlin J", dept: "ECE", employer: "Twozoo Tech Pvt Ltd – Chennai", type: "On Campus", salary: "2.76 LPA" },
  { sno: 56, name: "MuthuEswari V", dept: "ECE", employer: "Twozoo Tech Pvt Ltd – Chennai", type: "On Campus", salary: "2.76 LPA" },
  { sno: 57, name: "Sanini V", dept: "ECE", employer: "Twozoo Tech Pvt Ltd – Chennai", type: "On Campus", salary: "2.76 LPA" },
  { sno: 58, name: "Sibi Lingam S", dept: "ECE", employer: "Twozoo Tech Pvt Ltd – Chennai", type: "On Campus", salary: "2.76 LPA" },
  { sno: 59, name: "Nivetha M", dept: "ECE", employer: "Datayann – Chennai", type: "Off Campus", salary: "2.4 LPA" },
  { sno: 60, name: "Siblingam", dept: "ECE", employer: "Datapatterns – Chennai", type: "On Campus", salary: "3 LPA" },
  { sno: 61, name: "Mathesh T", dept: "ECE", employer: "Revol Software Pvt Ltd-Kanyakumari", type: "Off Campus", salary: "2.16 LPA" },
  { sno: 62, name: "MuthuRamalingam B", dept: "ECE", employer: "UTH Dev Holding Software Services", type: "On Campus", salary: "2.4 LPA" },
  { sno: 63, name: "Bhagavarthan B", dept: "EEE", employer: "Twozoo Tech Pvt Ltd – Chennai", type: "On Campus", salary: "2.76 LPA" },
  { sno: 64, name: "Muthupriya S", dept: "EEE", employer: "Twozoo Tech Pvt Ltd – Chennai", type: "On Campus", salary: "2.76 LPA" },
  { sno: 65, name: "K. Siva Somasundar", dept: "EEE", employer: "Electrical Engineers Pvt Ltd – Chennai", type: "Off Campus", salary: "2.1 LPA" },
  { sno: 66, name: "M. Balaji", dept: "EEE", employer: "Electrical Engineers Pvt Ltd – Chennai", type: "Off Campus", salary: "2.1 LPA" },
  { sno: 67, name: "Kaliraja", dept: "EEE", employer: "Electrical Engineers Pvt Ltd – Chennai", type: "Off Campus", salary: "2.1 LPA" },
  { sno: 68, name: "Mahesh Selvam P", dept: "Mech", employer: "MSR India Pvt Ltd – Chennai", type: "On Campus", salary: "1.6 LPA" },
  { sno: 69, name: "Kishore", dept: "Mech", employer: "Alba Trimina", type: "Off Campus", salary: "1.5 LPA" },
  { sno: 70, name: "Chidambaram", dept: "Mech", employer: "CKB Group", type: "Off Campus", salary: "2 LPA" },
  { sno: 71, name: "Abdul Rahuman Khan J", dept: "Mech", employer: "Datayam – Chennai", type: "Off Campus", salary: "2.4 LPA" },
  { sno: 72, name: "Krishna Veni", dept: "Civil", employer: "Aarbec Structures – Bangalore", type: "Off Campus", salary: "4 LPA" },
  { sno: 73, name: "Shifana", dept: "IT", employer: "PEN", type: "Off Campus", salary: "3 LPA" },
  { sno: 74, name: "K. Jeya Subramanian", dept: "CSE", employer: "BahwanCybertek", type: "Off Campus", salary: "3.5 LPA" },
  { sno: 75, name: "R. Maheswaran", dept: "IT", employer: "Newamrican Funding", type: "Off Campus", salary: "7.5 LPA" },
  { sno: 76, name: "EsakkiShanmuga Raja P", dept: "Civil", employer: "SSN & CO – Erode", type: "On Campus", salary: "1.8 LPA" },
  { sno: 77, name: "Jesuraj T", dept: "Civil", employer: "SSN & CO – Erode", type: "On Campus", salary: "1.8 LPA" },
  { sno: 78, name: "Rahulraj P", dept: "Civil", employer: "SSN & CO – Erode", type: "On Campus", salary: "1.8 LPA" },
  { sno: 79, name: "Gokulan A", dept: "Civil", employer: "SSN & CO – Erode", type: "On Campus", salary: "1.8 LPA" }
];


export const placementData2023_2024 = [
  { sno: 1, name: "P. Saravanan", dept: "CSE", employer: "Sure Soft", type: "On Campus", salary: "2.7 LPA" },
  { sno: 2, name: "Jasper GiftyVijayan", dept: "CSE", employer: "TECH HIVE Technology", type: "Off Campus", salary: "1.2 LPA" },
  { sno: 3, name: "M. Aswin", dept: "CSE", employer: "Webberax", type: "On Campus", salary: "3.12 LPA" },
  { sno: 4, name: "R.A. MitlanDepak", dept: "CSE", employer: "Webberax", type: "On Campus", salary: "3.12 LPA" },
  { sno: 5, name: "P. SubithaParvathi", dept: "CSE", employer: "Webberax", type: "On Campus", salary: "3.12 LPA" },
  { sno: 6, name: "R. Mano Venkateshwari", dept: "CSE", employer: "Webberax", type: "On Campus", salary: "3.12 LPA" },
  { sno: 7, name: "V. Eniha", dept: "CSE", employer: "Datayaan", type: "Off Campus", salary: "2.8 LPA" },
  { sno: 8, name: "A. Atchaya Lakshmi", dept: "CSE", employer: "Datayaan", type: "Off Campus", salary: "2.8 LPA" },
  { sno: 9, name: "S. Anjali", dept: "CSE", employer: "Coda Technology Solutions", type: "On Campus", salary: "1.92 LPA" },
  { sno: 10, name: "J.P. Preethika", dept: "CSE", employer: "Coda Technology Solutions", type: "On Campus", salary: "1.92 LPA" },
  { sno: 11, name: "A. Selvaveni", dept: "CSE", employer: "Coda Technology Solutions", type: "On Campus", salary: "1.92 LPA" },
  { sno: 12, name: "N. Pavithra", dept: "CSE", employer: "Coda Technology Solutions", type: "On Campus", salary: "1.92 LPA" },
  { sno: 13, name: "Sornalatha A", dept: "CSE", employer: "Ascending Software", type: "On Campus", salary: "1 LPA" },
  { sno: 14, name: "Jefferson James C", dept: "CSE", employer: "Ascending Software", type: "On Campus", salary: "1 LPA" },
  { sno: 15, name: "Hari Narayanan S", dept: "CSE", employer: "Ascending Software", type: "On Campus", salary: "1 LPA" },
  { sno: 16, name: "Maharajan P", dept: "CSE", employer: "Ascending Software", type: "On Campus", salary: "1 LPA" },
  { sno: 17, name: "JeyabalanKarthick S", dept: "CSE", employer: "Ascending Software", type: "On Campus", salary: "1 LPA" },
  { sno: 18, name: "G. Karthik Raja", dept: "CSE", employer: "Rinex Technologies", type: "Off Campus", salary: "3 LPA" },
  { sno: 19, name: "A.Velukumarasamy", dept: "CSE", employer: "Ascending Software", type: "On Campus", salary: "1 LPA" },
  { sno: 20, name: "S. AnuSelvi", dept: "ECE", employer: "Sure Soft", type: "On Campus", salary: "2.7 LPA" },
  { sno: 21, name: "T Sutharsan", dept: "ECE", employer: "Sure Soft", type: "On Campus", salary: "2.7 LPA" },
  { sno: 22, name: "Sowmiya S", dept: "ECE", employer: "Maxvy Technologies", type: "On Campus", salary: "2.5 LPA" },
  { sno: 23, name: "AlaguSathish M", dept: "ECE", employer: "Revol Software", type: "On Campus", salary: "1.8 LPA" },
  { sno: 24, name: "Malini P", dept: "ECE", employer: "Revol Software", type: "On Campus", salary: "1.8 LPA" },
  { sno: 25, name: "M. Maharajan", dept: "ECE", employer: "Coda Technology Solutions", type: "On Campus", salary: "1.92 LPA" },
  { sno: 26, name: "A.S. SawthaSafreena", dept: "ECE", employer: "Coda Technology Solutions", type: "On Campus", salary: "1.80 LPA" },
  { sno: 27, name: "R. Beaula", dept: "ECE", employer: "Coda Technology Solutions", type: "On Campus", salary: "1.92 LPA" },
  { sno: 28, name: "M. Jegadhees", dept: "ECE", employer: "Sansel Instruments and Control", type: "Off Campus", salary: "1.80 LPA" },
  { sno: 29, name: "P. Shenbagavalli", dept: "ECE", employer: "Ascending Software", type: "On Campus", salary: "1 LPA" },
  { sno: 30, name: "J. JenilJeba Ephraim", dept: "ECE", employer: "ZF Commercial Vehicle Control Systems India Limited", type: "Off Campus", salary: "2.4 LPA" },
  { sno: 31, name: "K. Nishanth", dept: "ECE", employer: "ZF Commercial Vehicle Control Systems India Limited", type: "Off Campus", salary: "2.4 LPA" },
  { sno: 32, name: "Ambicka Shri Sakthi", dept: "IT", employer: "iLinkMutitech Solutions", type: "Off Campus", salary: "1.20 LPA" },
  { sno: 33, name: "Sathananthan C", dept: "IT", employer: "Revol Software", type: "On Campus", salary: "1.8 LPA" },
  { sno: 34, name: "L. Jeyasarathy", dept: "IT", employer: "Rinex Technologies", type: "Off Campus", salary: "3 LPA" },
  { sno: 35, name: "A. Rajiv Gandhi", dept: "IT", employer: "Coda Technology Solutions", type: "On Campus", salary: "1.92 LPA" },
  { sno: 36, name: "R. Prakashini", dept: "IT", employer: "Coda Technology Solutions", type: "On Campus", salary: "1.92 LPA" },
  { sno: 37, name: "R. AlaguSundari", dept: "IT", employer: "Ascending Software", type: "On Campus", salary: "1 LPA" },
  { sno: 38, name: "PonPapitha G", dept: "IT", employer: "Ascending Software", type: "On Campus", salary: "1 LPA" },
  { sno: 39, name: "Suvetha M", dept: "IT", employer: "Ascending Software", type: "On Campus", salary: "1 LPA" },
  { sno: 40, name: "AlwinJesuraj E", dept: "IT", employer: "Ascending Software", type: "On Campus", salary: "1 LPA" },
  { sno: 41, name: "Kaviya J", dept: "IT", employer: "Ascending Software", type: "On Campus", salary: "1 LPA" },
  { sno: 42, name: "V. MuthuSankar", dept: "CIVIL", employer: "Arc Planner and Engineers", type: "On Campus", salary: "1.44 LPA" },
  { sno: 43, name: "S. Mohamed Shahid", dept: "CIVIL", employer: "Arc Planner and Engineers", type: "On Campus", salary: "1.44 LPA" },
  { sno: 44, name: "R. Muthupriya", dept: "CIVIL", employer: "Arc Planner and Engineers", type: "On Campus", salary: "1.44 LPA" },
  { sno: 45, name: "C. Shri DivyaLaxmi", dept: "CIVIL", employer: "Arc Planner and Engineers", type: "On Campus", salary: "1.44 LPA" },
  { sno: 46, name: "L. Sri Santhana Lakshmi", dept: "CIVIL", employer: "Arc Planner and Engineers", type: "On Campus", salary: "1.44 LPA" },
  { sno: 47, name: "S. Kannan", dept: "CIVIL", employer: "SAS CAD Service", type: "Off Campus", salary: "1.8 LPA" },
  { sno: 48, name: "K. Muthu Surya", dept: "CIVIL", employer: "SAS CAD Service", type: "Off Campus", salary: "1.8 LPA" },
  { sno: 49, name: "K. DhanaSundar", dept: "CIVIL", employer: "SAS CAD Service", type: "Off Campus", salary: "1.8 LPA" },
  { sno: 50, name: "VijayaHarsitha M", dept: "CIVIL", employer: "Aarbee Structures Pvt. Ltd.", type: "Off Campus", salary: "2.52 LPA" },
  { sno: 51, name: "AngalaEswari N", dept: "EEE", employer: "Timken", type: "On Campus", salary: "2.5 LPA" },
  { sno: 52, name: "Guru Manikandan", dept: "EEE", employer: "Timken", type: "On Campus", salary: "2.5 LPA" },
  { sno: 53, name: "Ajith Kumar", dept: "EEE", employer: "Timken", type: "On Campus", salary: "2.5 LPA" },
  { sno: 54, name: "K. Sankar", dept: "EEE", employer: "Coda Technology Solutions", type: "On Campus", salary: "1.92 LPA" },
  { sno: 55, name: "R. GowthamKanna", dept: "EEE", employer: "ZF Commercial Vehicle Control Systems India Limited", type: "Off Campus", salary: "2.4 LPA" },
  { sno: 56, name: "N. BalaAbishek", dept: "EEE", employer: "ZF Commercial Vehicle Control Systems India Limited", type: "Off Campus", salary: "2.4 LPA" },
  { sno: 57, name: "C. Abishekdurai", dept: "EEE", employer: "ZF Commercial Vehicle Control Systems India Limited", type: "Off Campus", salary: "2.4 LPA" },
  { sno: 58, name: "S. GiftsonDharmaraj", dept: "EEE", employer: "Protorix", type: "Off Campus", salary: "1.20 LPA" },
  { sno: 59, name: "P. ManikandaPrabu", dept: "EEE", employer: "Astra Aero", type: "Off Campus", salary: "2.2 LPA" },
  { sno: 60, name: "M. Maheswari", dept: "MECH", employer: "Timken", type: "On Campus", salary: "2.5 LPA" },
  { sno: 61, name: "K. Santhosh Kumar", dept: "MECH", employer: "Timken", type: "On Campus", salary: "2.5 LPA" },
  { sno: 62, name: "S. PonMahendran", dept: "MECH", employer: "Coda Technology Solutions", type: "On Campus", salary: "1.92 LPA" },
  { sno: 63, name: "R.S. Prakash", dept: "MECH", employer: "Coda Technology Solutions", type: "On Campus", salary: "1.80 LPA" },
  { sno: 64, name: "N. Abisheik", dept: "MECH", employer: "ZF Commercial Vehicle Control Systems India Limited", type: "Off Campus", salary: "2.4 LPA" },
  { sno: 65, name: "M. Kamalesh Kumar", dept: "MECH", employer: "ZF Commercial Vehicle Control Systems India Limited", type: "Off Campus", salary: "2.4 LPA" },
  { sno: 66, name: "S. Godwin", dept: "MECH", employer: "Windcare", type: "On Campus", salary: "2.12 LPA" },
  { sno: 67, name: "A. BharathiSrimathi", dept: "MBA", employer: "Coda Technology Solutions", type: "On Campus", salary: "1.30 LPA" },
  { sno: 68, name: "AmeenaMusharafa M.R", dept: "MBA", employer: "Centizen Inc.", type: "Off Campus", salary: "2.4 LPA" },
  { sno: 69, name: "Sri Aruna N", dept: "MBA", employer: "Reliance Retail", type: "Off Campus", salary: "2.12 LPA" },
  { sno: 70, name: "Marimuthu S", dept: "MBA", employer: "Reliance Retail", type: "Off Campus", salary: "2.12 LPA" },
  { sno: 71, name: "Vinashini T", dept: "MBA", employer: "Reliance Retail", type: "Off Campus", salary: "2.12 LPA" },
  { sno: 72, name: "Deepika U", dept: "VLSI", employer: "Mistral Solutions", type: "On Campus", salary: "5 LPA" }
];



export const placementData2024_2025 = [
  { sno: "1", name: "Felci Veronica S", dept: "CSE", employer: "Mitsogo, Trivandrum", type: "ON Campus", salary: "4 LPA" },
  { sno: "2", name: "Julian B", dept: "CSE", employer: "Exalca, Chennai", type: "OFF Campus", salary: "3 LPA" },
  { sno: "3", name: "A R Anusuyaa baby", dept: "CSE", employer: "VI Microsystems Pvt Ltd, Chennai", type: "ON Campus", salary: "1.8 LPA" },
  { sno: "3", name: "A R Anusuyaa baby", dept: "CSE", employer: "Vintorix, Chennai", type: "ON Campus", salary: "3.12 LPA" },
  { sno: "4", name: "R.Kavidharsha", dept: "CSE", employer: "VI Microsystems Pvt Ltd, Chennai", type: "ON Campus", salary: "1.8 LPA" },
  { sno: "5", name: "B.Yamuna", dept: "CSE", employer: "VI Microsystems Pvt Ltd, Chennai", type: "ON Campus", salary: "1.8 LPA" },
  { sno: "5", name: "B.Yamuna", dept: "CSE", employer: "Vintorix, Chennai", type: "ON Campus", salary: "3.12 LPA" },
  { sno: "6", name: "Vaishna S", dept: "CSE", employer: "OneyesInfotech, Chennai", type: "ON Campus", salary: "4 LPA" },
  { sno: "6", name: "Vaishna S", dept: "CSE", employer: "Icanio-Tirunelveli", type: "ON Campus", salary: "2.5 LPA" },
  { sno: "7", name: "Aishwarya C", dept: "CSE", employer: "OneyesInfotech, Chennai", type: "ON Campus", salary: "4 LPA" },
  { sno: "8", name: "Mari Selvam S", dept: "CSE", employer: "OneyesInfotech, Chennai", type: "ON Campus", salary: "4 LPA" },
  { sno: "9", name: "Gunasunthari M", dept: "CSE", employer: "OneyesInfotech, Chennai", type: "ON Campus", salary: "4 LPA" },
  { sno: "10", name: "BalaRamya K", dept: "CSE", employer: "Techvolt Software, Coimbatore", type: "ON Campus", salary: "2.4 LPA" },
  { sno: "10", name: "BalaRamya K", dept: "CSE", employer: "Suresoft, Pondicherry", type: "ON Campus", salary: "2.7 LPA" },
  { sno: "11", name: "Kavitha Shree V", dept: "CSE", employer: "Techvolt Software, Coimbatore", type: "ON Campus", salary: "2.4 LPA" },
  { sno: "12", name: "Abdullah Fairz I", dept: "CSE", employer: "Techvolt Software, Coimbatore", type: "ON Campus", salary: "2.4 LPA" },
  { sno: "13", name: "Rashathi A", dept: "CSE", employer: "Techvolt Software, Coimbatore", type: "ON Campus", salary: "2.4 LPA" },
  { sno: "14", name: "Jasper D", dept: "CSE", employer: "Techvolt Software, Coimbatore", type: "ON Campus", salary: "2.4 LPA" },
  { sno: "15", name: "Aswini P", dept: "CSE", employer: "Talent Turbo Technologies, Nagercoil", type: "ON Campus", salary: "3 LPA" },
  { sno: "16", name: "Smiruti R", dept: "CSE", employer: "Talent Turbo Technologies, Nagercoil", type: "ON Campus", salary: "3 LPA" },
  { sno: "17", name: "Petchimuthu M", dept: "CSE", employer: "Keykoders, Tirunelveli", type: "NaanMudhalvan", salary: "2 LPA" },
  { sno: "18", name: "Santhosh M", dept: "CSE", employer: "Coda Technology Solutions, Chennai", type: "ON Campus", salary: "1.8 LPA" },
  { sno: "19", name: "MuthuBhuvanesh R", dept: "CSE", employer: "Sensen Service, Srivaikundam", type: "ON Campus", salary: "2 LPA" },
  { sno: "20", name: "Kawin S V", dept: "CSE", employer: "Sensen Service, Srivaikundam", type: "ON Campus", salary: "2 LPA" },
  { sno: "21", name: "AlfiRomitha", dept: "CSE", employer: "Sensen Service, Srivaikundam", type: "ON Campus", salary: "2 LPA" },
  { sno: "22", name: "DIVYA BARATHI A", dept: "CSE", employer: "Digisailor", type: "NaanMudhalvan", salary: "2 LPA" },
  { sno: "23", name: "SUBANANDHINI S", dept: "CSE", employer: "Digisailor", type: "NaanMudhalvan", salary: "2 LPA" },
  { sno: "24", name: "Nishanthi A", dept: "CSE", employer: "Suresoft, Pondicherry", type: "ON Campus", salary: "2.7 LPA" },
  { sno: "25", name: "Sangeetha K", dept: "CSE", employer: "Suresoft, Pondicherry", type: "ON Campus", salary: "2.7 LPA" },
  { sno: "26", name: "Archana R", dept: "CSE", employer: "Vintorix, Chennai", type: "ON Campus", salary: "3.12 LPA" },
  { sno: "27", name: "Dhanushya N", dept: "CSE", employer: "Vintorix, Chennai", type: "ON Campus", salary: "3.12 LPA" },
  { sno: "28", name: "Suganya M", dept: "CSE", employer: "Vintorix, Chennai", type: "ON Campus", salary: "3.12 LPA" },
  { sno: "29", name: "SathakYousuf P M", dept: "CSE", employer: "Smackoders, Tirunelveli", type: "ON Campus", salary: "1.8 LPA" },
  { sno: "30", name: "Akash k", dept: "CSE", employer: "Smackoders, Tirunelveli", type: "ON Campus", salary: "1.8 LPA" },
  { sno: "31", name: "AntoAnisten A", dept: "CSE", employer: "Smackoders, Tirunelveli", type: "ON Campus", salary: "1.8 LPA" },
  { sno: "32", name: "Joe Roseny J", dept: "ECE", employer: "Centizen, Tirunelveli", type: "ON Campus", salary: "2.16 LPA" },
  { sno: "33", name: "Abisha Shree T", dept: "ECE", employer: "Centizen, Tirunelveli", type: "ON Campus", salary: "2.16 LPA" },
  { sno: "34", name: "Godrick M", dept: "ECE", employer: "VI Microsystems Pvt Ltd, Chennai", type: "ON Campus", salary: "1.8 LPA" },
  { sno: "35", name: "Sujin A", dept: "ECE", employer: "AVALON Technologies, Chennai", type: "OFF Campus", salary: "3 LPA" },
  { sno: "35", name: "Sujin A", dept: "ECE", employer: "VI Microsystems Pvt Ltd, Chennai", type: "ON Campus", salary: "1.8 LPA" },
  { sno: "35", name: "Sujin A", dept: "ECE", employer: "Techvolt Software, Coimbatore", type: "ON Campus", salary: "2.4 LPA" },
  { sno: "35", name: "Sujin A", dept: "ECE", employer: "Classic Manpower Operations Pvt Ltd, Chennai", type: "NaanMudhalvan", salary: "2.4 LPA" },
  { sno: "36", name: "Iyyappan Ganesh P", dept: "ECE", employer: "VI Microsystems Pvt Ltd, Chennai", type: "ON Campus", salary: "1.8 LPA" },
  { sno: "36", name: "Iyyappan Ganesh P", dept: "ECE", employer: "Recynergy, Chennai", type: "Virtual", salary: "2.4 LPA" },
  { sno: "36", name: "Iyyappan Ganesh P", dept: "ECE", employer: "Classic Manpower Operations Pvt Ltd, Chennai", type: "NaanMudhalvan", salary: "2.4 LPA" },
  { sno: "37", name: "Uma Jothiswari I", dept: "ECE", employer: "VI Microsystems Pvt Ltd, Chennai", type: "ON Campus", salary: "1.8 LPA" },
  { sno: "37", name: "Uma Jothiswari I", dept: "ECE", employer: "Classic Manpower Operations Pvt Ltd, Chennai", type: "NaanMudhalvan", salary: "2.4 LPA" },
  { sno: "37", name: "Uma Jothiswari I", dept: "ECE", employer: "Techvolt Software, Coimbatore", type: "ON Campus", salary: "2.4 LPA" },
  { sno: "38", name: "Rishvana S", dept: "ECE", employer: "Coda Technology Solutions, Chennai", type: "ON Campus", salary: "2 LPA" },
  { sno: "39", name: "Vinothini S", dept: "ECE", employer: "Classic Manpower Operations Pvt Ltd, Chennai", type: "NaanMudhalvan", salary: "2.4 LPA" },
  { sno: "39", name: "Vinothini S", dept: "ECE", employer: "Bhert Robotics, Banglore", type: "ON Campus", salary: "2 LPA" },
  { sno: "39", name: "Vinothini S", dept: "ECE", employer: "Classic Manpower Operations Pvt Ltd, Chennai", type: "NaanMudhalvan", salary: "2.4 LPA" },
  { sno: "40", name: "SaiPushkala N", dept: "ECE", employer: "Techvolt Software, Coimbatore", type: "ON Campus", salary: "2.4 LPA" },
  { sno: "41", name: "MathanMukesh A", dept: "ECE", employer: "Sensenservice, Srivaikundam", type: "ON Campus", salary: "2.4 LPA" },
  { sno: "42", name: "Sudheesh R", dept: "ECE", employer: "Sensenservice, Srivaikundam", type: "ON Campus", salary: "2.4 LPA" },
  { sno: "43", name: "Ponmathankumar T", dept: "ECE", employer: "Sensenservice, Srivaikundam", type: "ON Campus", salary: "2.4 LPA" },
  { sno: "44", name: "Yogeshwaran M", dept: "ECE", employer: "Sensenservice, Srivaikundam", type: "ON Campus", salary: "2.4 LPA" },
  { sno: "45", name: "Vishnuprasath P", dept: "ECE", employer: "Recynergy, Chennai", type: "Company Direct", salary: "2.4 LPA" },
  { sno: "45", name: "Vishnuprasath P", dept: "ECE", employer: "Classic Manpower Operations Pvt Ltd, Chennai", type: "NaanMudhalvan", salary: "2.4 LPA" },
  { sno: "46", name: "Sakthivel I", dept: "ECE", employer: "Recynergy, Chennai", type: "Company Direct", salary: "2.4 LPA" },
  { sno: "46", name: "Sakthivel I", dept: "ECE", employer: "Classic Manpower Operations Pvt Ltd, Chennai", type: "NaanMudhalvan", salary: "2.4 LPA" },
  { sno: "47", name: "Saranya R", dept: "ECE", employer: "Techvolt Software, Coimbatore", type: "ON Campus", salary: "2.4 LPA" },
  { sno: "47", name: "Saranya R", dept: "ECE", employer: "Classic Manpower Operations Pvt Ltd, Chennai", type: "NaanMudhalvan", salary: "2.4 LPA" },
  { sno: "48", name: "Sriram R", dept: "ECE", employer: "Techvolt Software, Coimbatore", type: "ON Campus", salary: "2.4 LPA" },
  { sno: "48", name: "Sriram R", dept: "ECE", employer: "Classic Manpower Operations Pvt Ltd, Chennai", type: "NaanMudhalvan", salary: "2.4 LPA" },
  { sno: "49", name: "MuthuSumitha P", dept: "ECE", employer: "Techvolt Software, Coimbatore", type: "ON Campus", salary: "2.4 LPA" },
  { sno: "49", name: "MuthuSumitha P", dept: "ECE", employer: "Classic Manpower Operations Pvt Ltd, Chennai", type: "NaanMudhalvan", salary: "2.4 LPA" },
  { sno: "50", name: "Anushya I", dept: "ECE", employer: "Classic Manpower Operations Pvt Ltd, Chennai", type: "NaanMudhalvan", salary: "2.4 LPA" },
  { sno: "50", name: "Anushya I", dept: "ECE", employer: "Bhert Robotics, Banglore", type: "ON Campus", salary: "2 LPA" },
  { sno: "51", name: "ShanmugaGomathy P", dept: "ECE", employer: "Talent Turbo Technologies, Nagercoil", type: "ON Campus", salary: "3 LPA" },
  { sno: "52", name: "Muthukrishnansaravanan P", dept: "ECE", employer: "Talent Turbo Technologies, Nagercoil", type: "ON Campus", salary: "3 LPA" },
  { sno: "53", name: "Joben B", dept: "ECE", employer: "Coda Technology Solutions, Chennai", type: "ON Campus", salary: "2 LPA" },
  { sno: "53", name: "Joben B", dept: "ECE", employer: "Classic Manpower Operations Pvt Ltd, Chennai", type: "NaanMudhalvan", salary: "2.4 LPA" },
  { sno: "54", name: "ArlinSoniya D", dept: "ECE", employer: "Classic Manpower Operations Pvt Ltd, Chennai", type: "NaanMudhalvan", salary: "2.4 LPA" },
  { sno: "55", name: "Lakshmi Priyadharshini P", dept: "ECE", employer: "Delphi TVS, Chennai", type: "NaanMudhalvan", salary: "2.57 LPA" },
  { sno: "55", name: "Lakshmi Priyadharshini P", dept: "ECE", employer: "ZF Commercial Vehicle Control Systems, Chennai", type: "OFF Campus", salary: "2.28 LPA" },
  { sno: "55", name: "Lakshmi Priyadharshini P", dept: "ECE", employer: "Classic Manpower Operations Pvt Ltd, Chennai", type: "NaanMudhalvan", salary: "2.4 LPA" },
  { sno: "56", name: "SherlineRenisha", dept: "ECE", employer: "ZF Commercial Vehicle Control Systems, Chennai", type: "OFF Campus", salary: "2.28 LPA" },
  { sno: "57", name: "Blessy Y", dept: "EEE", employer: "Coda Technology Solutions, Chennai", type: "ON Campus", salary: "2 LPA" },
  { sno: "58", name: "M.Surenthar", dept: "EEE", employer: "VI Microsystems Pvt Ltd, Chennai", type: "ON Campus", salary: "1.8 LPA" },
  { sno: "59", name: "Aravinth A", dept: "EEE", employer: "VI Microsystems Pvt Ltd, Chennai", type: "ON Campus", salary: "1.8 LPA" },
  { sno: "60", name: "Aruljose C", dept: "EEE", employer: "Delphi TVS, Chennai", type: "NaanMudhalvan", salary: "2.57 LPA" },
  { sno: "60", name: "Aruljose C", dept: "EEE", employer: "METEC, Chennai", type: "OFF Campus", salary: "2.16 LPA" },
  { sno: "60", name: "Aruljose C", dept: "EEE", employer: "VI Microsystems Pvt Ltd, Chennai", type: "ON Campus", salary: "1.8 LPA" },
  { sno: "61", name: "MohamedArsath A", dept: "EEE", employer: "Delphi TVS, Chennai", type: "NaanMudhalvan", salary: "2.57 LPA" },
  { sno: "61", name: "MohamedArsath A", dept: "EEE", employer: "Microsystems Pvt Ltd, Chennai", type: "ON Campus", salary: "1.8 LPA" },
  { sno: "62", name: "Gayathri P", dept: "EEE", employer: "Delphi TVS, Chennai", type: "NaanMudhalvan", salary: "2.57 LPA" },
  { sno: "62", name: "Gayathri P", dept: "EEE", employer: "Coda Technology Solutions, Chennai", type: "ON Campus", salary: "2 LPA" },
  { sno: "62", name: "Gayathri P", dept: "EEE", employer: "ZF Commercial Vehicle Control Systems, Chennai", type: "Company Direct", salary: "2.28 LPA" },
  { sno: "63", name: "Saranya V", dept: "EEE", employer: "Delphi TVS, Chennai", type: "NaanMudhalvan", salary: "2.57 LPA" },
  { sno: "63", name: "Saranya V", dept: "EEE", employer: "ZF Commercial Vehicle Control Systems, Chennai", type: "", salary: "2.28 LPA" },
  { sno: "64", name: "Monica E", dept: "EEE", employer: "OneyesInfotech, Chennai", type: "ON Campus", salary: "4 LPA" },
  { sno: "65", name: "Parath Surya V J", dept: "EEE", employer: "OneyesInfotech, Chennai", type: "ON Campus", salary: "4 LPA" },
  { sno: "65", name: "Parath Surya V J", dept: "EEE", employer: "ZF Commercial Vehicle Control Systems, Chennai", type: "Company Direct", salary: "2.28 LPA" },
  { sno: "66", name: "Subalakshmi M", dept: "EEE", employer: "Techvolt Software, Coimbatore", type: "ON Campus", salary: "2.4 LPA" },
  { sno: "67", name: "JeyaBharathi R", dept: "EEE", employer: "Techvolt Software, Coimbatore", type: "ON Campus", salary: "2.4 LPA" },
  { sno: "67", name: "JeyaBharathi R", dept: "EEE", employer: "Delphi TVS, Chennai", type: "NaanMudhalvan", salary: "2.57 LPA" },
  { sno: "67", name: "JeyaBharathi R", dept: "EEE", employer: "ZF Commercial Vehicle Control Systems, Chennai", type: "Company Direct", salary: "2.28 LPA" },
  { sno: "68", name: "Muthu Monica M", dept: "EEE", employer: "Techvolt Software, Coimbatore", type: "ON Campus", salary: "2.4 LPA" },
  { sno: "68", name: "Muthu Monica M", dept: "EEE", employer: "Coda Technology Solutions, Chennai", type: "ON Campus", salary: "2 LPA" },
  { sno: "69", name: "Praveen Bharath N", dept: "EEE", employer: "Delphi TVS, Chennai", type: "NaanMudhalvan", salary: "2.57 LPA" },
  { sno: "69", name: "Praveen Bharath N", dept: "EEE", employer: "METEC, Chennai", type: "OFF Campus", salary: "2.16 LPA" },
  { sno: "70", name: "Harikaran S", dept: "EEE", employer: "Talent Turbo Technologies, Nagercoil", type: "ON Campus", salary: "3 LPA" },
  { sno: "71", name: "Ramalakshmi P", dept: "EEE", employer: "Delphi TVS, Chennai", type: "NaanMudhalvan", salary: "2.57 LPA" },
  { sno: "71", name: "Ramalakshmi P", dept: "EEE", employer: "ZF Commercial Vehicle Control Systems, Chennai", type: "Company Direct", salary: "2.28 LPA" },
  { sno: "72", name: "Sowbagya M", dept: "EEE", employer: "Delphi TVS, Chennai", type: "NaanMudhalvan", salary: "2.57 LPA" },
  { sno: "72", name: "Sowbagya M", dept: "EEE", employer: "ZF Commercial Vehicle Control Systems, Chennai", type: "Company Direct", salary: "2.28 LPA" },
  { sno: "73", name: "Subalakshmi N", dept: "EEE", employer: "Delphi TVS, Chennai", type: "NaanMudhalvan", salary: "2.57 LPA" },
  { sno: "74", name: "Ancy Raja Jose S", dept: "EEE", employer: "Delphi TVS, Chennai", type: "NaanMudhalvan", salary: "2.57 LPA" },
  { sno: "74", name: "Ancy Raja Jose S", dept: "EEE", employer: "ZF Commercial Vehicle Control Systems, Chennai", type: "Company Direct", salary: "2.28 LPA" },
  { sno: "75", name: "JerffinBlessy J", dept: "EEE", employer: "Delphi TVS, Chennai", type: "NaanMudhalvan", salary: "2.57 LPA" },
  { sno: "75", name: "JerffinBlessy J", dept: "EEE", employer: "Trimed Technologies", type: "Company Direct", salary: "2.4 LPA" },
  { sno: "76", name: "Durgadevi C", dept: "EEE", employer: "Delphi TVS, Chennai", type: "NaanMudhalvan", salary: "2.57 LPA" },
  { sno: "77", name: "Balakrishnan.K", dept: "EEE", employer: "ZF Commercial Vehicle Control Systems, Chennai", type: "Company Direct", salary: "2.28 LPA" },
  { sno: "78", name: "Veena M", dept: "EEE", employer: "Delphi TVS, Chennai", type: "NaanMudhalvan", salary: "2.57 LPA" },
  { sno: "78", name: "Veena M", dept: "EEE", employer: "ZF Commercial Vehicle Control Systems, Chennai", type: "Company Direct", salary: "2.28 LPA" },
  { sno: "79", name: "Deniston Ragland W", dept: "EEE", employer: "Delphi TVS, Chennai", type: "NaanMudhalvan", salary: "2.57 LPA" },
  { sno: "79", name: "Deniston Ragland W", dept: "EEE", employer: "ZF Commercial Vehicle Control Systems, Chennai", type: "Company Direct", salary: "2.28 LPA" },
  { sno: "80", name: "Dhanush Raja J K", dept: "EEE", employer: "Delphi TVS, Chennai", type: "NaanMudhalvan", salary: "2.57 LPA" },
  { sno: "80", name: "Dhanush Raja J K", dept: "EEE", employer: "ZF Commercial Vehicle Control Systems, Chennai", type: "Company Direct", salary: "2.28 LPA" },
  { sno: "81", name: "Rajasekar S", dept: "EEE", employer: "Delphi TVS, Chennai", type: "NaanMudhalvan", salary: "2.57 LPA" },
  { sno: "81", name: "Rajasekar S", dept: "EEE", employer: "ZF Commercial Vehicle Control Systems, Chennai", type: "Company Direct", salary: "2.28 LPA" },
  { sno: "82", name: "Bavin Raj B", dept: "EEE", employer: "ZF Commercial Vehicle Control Systems, Chennai", type: "Company Direct", salary: "2.28 LPA" },
  { sno: "83", name: "Vasanth E", dept: "EEE", employer: "ZF Commercial Vehicle Control Systems, Chennai", type: "Company Direct", salary: "2.28 LPA" },
  { sno: "84", name: "Ariakash S", dept: "IT", employer: "Centizen, Tirunelveli", type: "ON Campus", salary: "3.07 LPA" },
  { sno: "85", name: "M.AnandhPriyaDharshini", dept: "IT", employer: "VI Microsystems Pvt Ltd, Chennai", type: "ON Campus", salary: "1.8 LPA" },
  { sno: "86", name: "Siva Ganesh M", dept: "IT", employer: "Techvolt Software, Coimbatore", type: "ON Campus", salary: "2.4 LPA" },
  { sno: "87", name: "HrithikeshAdityan S", dept: "IT", employer: "Techvolt Software, Coimbatore", type: "ON Campus", salary: "2.4 LPA" },
  { sno: "88", name: "Sneka P", dept: "IT", employer: "Techvolt Software, Coimbatore", type: "ON Campus", salary: "2.4 LPA" },
  { sno: "89", name: "Iswarya A", dept: "IT", employer: "Techvolt Software, Coimbatore", type: "ON Campus", salary: "2.4 LPA" },
  { sno: "90", name: "Muthuram S", dept: "IT", employer: "Techvolt Software, Coimbatore", type: "ON Campus", salary: "2.4 LPA" },
  { sno: "91", name: "Libisha J G", dept: "IT", employer: "Talent Turbo Technologies, Nagercoil", type: "ON Campus", salary: "3 LPA" },
  { sno: "92", name: "Ashvini A", dept: "IT", employer: "Talent Turbo Technologies, Nagercoil", type: "ON Campus", salary: "3 LPA" },
  { sno: "93", name: "Aarthi Lakshmi N", dept: "IT", employer: "Keykoders, Tirunelveli", type: "NaanMudhalvan", salary: "2 LPA" },
  { sno: "94", name: "SakthiPraba M", dept: "IT", employer: "Keykoders, Tirunelveli", type: "NaanMudhalvan", salary: "2 LPA" },
  { sno: "95", name: "Priyadharshini C", dept: "IT", employer: "Sensen Service", type: "ON Campus", salary: "2.4 LPA" },
  { sno: "96", name: "EssaiRoobini P", dept: "IT", employer: "Digisailor", type: "NaanMudhalvan", salary: "2 LPA" },
  { sno: "97", name: "Mohan Ram A", dept: "IT", employer: "Suresoft", type: "ON Campus", salary: "2.7 LPA" },
  { sno: "98", name: "S KAMALESH KUMAR", dept: "IT", employer: "6SOLVE IT SERVICES", type: "Company Direct", salary: "1.9 LPA" },
  { sno: "99", name: "Chidambaraganapathi V", dept: "IT", employer: "Smackoders, Tirunelveli", type: "ON Campus", salary: "1.8 LPA" },
  { sno: "100", name: "HareshVisal", dept: "IT", employer: "Smackoders, Tirunelveli", type: "ON Campus", salary: "1.8 LPA" },
  { sno: "101", name: "SornaReefen Kumar R", dept: "Civil", employer: "Jehovah Nissi Design Build Pvt Ltd", type: "NaanMudhalvan", salary: "1.8 LPA" },
  { sno: "102", name: "Vishwa P", dept: "Civil", employer: "Jehovah Nissi Design Build Pvt Ltd", type: "NaanMudhalvan", salary: "1.8 LPA" },
  { sno: "103", name: "Arul Kumaran S", dept: "Civil", employer: "Maxzimus Steel Building P Ltd", type: "ON Campus", salary: "1.8 LPA" },
  { sno: "104", name: "Arun C", dept: "Civil", employer: "GMD VENTURE PRIVATE LIMITED", type: "ON Campus", salary: "1.8 LPA" },
  { sno: "105", name: "Renganathan S A", dept: "Civil", employer: "GMD VENTURE PRIVATE LIMITED", type: "ON Campus", salary: "1.8 LPA" },
  { sno: "106", name: "Venkatesh K", dept: "Civil", employer: "GMD VENTURE PRIVATE LIMITED", type: "ON Campus", salary: "1.8 LPA" },
  { sno: "107", name: "Balaji P", dept: "Civil", employer: "GMD VENTURE PRIVATE LIMITED", type: "ON Campus", salary: "1.8 LPA" },
  { sno: "108", name: "Joseph Jesnow J", dept: "Civil", employer: "S R Builders Projects LLP", type: "Virtual", salary: "1.8 LPA" },
  { sno: "109", name: "Regina P", dept: "Civil", employer: "Anugraha Design Consultant", type: "Virtual", salary: "1.8 LPA" },
  { sno: "110", name: "Sankara Narayanan G", dept: "Mech", employer: "Delphi TVS, Chennai", type: "NaanMudhalvan", salary: "2.57 LPA" },
  { sno: "111", name: "Samuel G", dept: "Mech", employer: "Delphi TVS, Chennai", type: "NaanMudhalvan", salary: "2.57 LPA" },
  { sno: "112", name: "HariChandran H", dept: "Mech", employer: "ZF Commercial Vehicle Control Systems, Chennai", type: "OFF Campus", salary: "2.28 LPA" },
  { sno: "113", name: "Sabareeswaran I", dept: "Mech", employer: "ZF Commercial Vehicle Control Systems, Chennai", type: "OFF Campus", salary: "2.28 LPA" },
  { sno: "114", name: "Pachammal S", dept: "Mech", employer: "Coda Technology Solutions, Chennai", type: "ON Campus", salary: "1.8 LPA" },
  { sno: "115", name: "Vignesh S", dept: "Mech", employer: "Maxzimus Steel Building P Ltd", type: "ON Campus", salary: "1.8 LPA" },
  { sno: "116", name: "Ravikumar K", dept: "Mech", employer: "Maxzimus Steel Building P Ltd", type: "ON Campus", salary: "1.8 LPA" },
  { sno: "117", name: "NavisPaulsma G", dept: "MBA", employer: "Centizen, Tirunelveli", type: "ON Campus", salary: "2.16 LPA" },
  { sno: "118", name: "Rukmani M", dept: "MBA", employer: "Techvolt Software, Coimbatore", type: "ON Campus", salary: "2.4 LPA" },
  { sno: "119", name: "Vasanth L", dept: "M.E. - VLSI", employer: "Sensenservice, Srivaikundam", type: "ON Campus", salary: "2.4 LPA" },
  { sno: "120", name: "NANCY SNOW MARY M", dept: "M.E. - VLSI", employer: "PRS Group", type: "Virtual", salary: "2.4 LPA" }
];

